# file path to neural network weights and model config
model_name: "GQCNN-4.0-PJ"
model_dir: "/home/trs/ros_ws/src/team-park/dependencies/dexnet_deps/gqcnn/models/GQCNN-4.0-PJ"
model_params: "/home/trs/ros_ws/src/team-park/dependencies/dexnet_deps/gqcnn/cfg/examples/replication/dex-net_4.0_pj.yaml"
